GET localhost:22080/

> {%
    client.test("See the list of products", function () {
        client.assert(response.status === 200, 'Status is OK');
    });

    const data = JSON.parse(response.body.trim());
    const productId = data['items'][0]['id'];
    client.log(`Set global productId to ${productId}`);
    client.global.set('productId', productId);
 %}

###

POST localhost:22080/orders

{
    "products": [
        {
            "id": "{{productId}}",
            "count": 2
        }
    ]
}

> {%

    client.test("The order has been created", function () {
        client.assert(response.status === 201, 'Status is Created');
    });

    const data = JSON.parse(response.body.trim());
    const orderId = data['order']['id'];
    client.log(`Set global orderId to ${orderId}`);
    client.global.set('orderId', orderId);
 %}
